$(document).ready(function(){
    $("#feat1").click(function(){
        $("#featMore-01").toggle(300);
    });
    $("#feat2").click(function(){
        $("#featMore-02").toggle(300);
    });
    $("#feat3").click(function(){
        $("#featMore-03").toggle(300);
    });
    $("#overMoreBtn").click(function(){
        $("#overMore").toggle(300);
    });
});